### ISSUE TITLE
PaymentRequests - stadig problemer med 1/1000 del af beløbet bliver opkrævet

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#12]
Der er stadig nogle issues med at beløbet ikke er korrekt, når man sender en payment request.
Nogle går rigtigt igennem og andre gør ikke.

- Det første beløb her var 2139kr og ikke 2,13kr.
- De næste 3 er korrekte.
- Dem på 1,27kr skulle være 1275kr.

![image](https://cloud.githubusercontent.com/assets/504236/20756558/68452d40-b713-11e6-888a-0d15d8aebbb9.png)

![image](https://cloud.githubusercontent.com/assets/504236/20756702/f76cf03e-b713-11e6-8001-c70a50efa7f8.png)
Ordren på 1275kr, som kun bliver opkrævet 1,27kr

**Comment by AllanWLie** [comment]
@m-overlund vi kan ikke genskabe det problem du beskriver.

**Comment by m-overlund** [comment]
Du kan se issue'et her: http://screencast.com/t/APY44z6q2

Jeg ved ikke hvad sammenhængen er mellem hvornår det sker og ikke gør.
Det kunne måske være ordrer som er annulleret/autocanceled i første omgang, og man herefter sender en payment request, at amount er forkert?

**Comment by AllanWLie** [comment]
@m-overlund Jeg har nu fundet problemet.  Problemet lå i at beløbet var med "," i stedet for "." hvilket man ikke i koden kan * med 100 for at konvertere det til minorunits. Denne fejl kommer med i næste release af modulet.
