### ISSUE TITLE
Ordrer kan skifte status tilbage til pending efter den er betalt.

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#13]
Ordrer kan skifte status tilbage til pending efter den er betalt. (v2.7.1)

![image](https://cloud.githubusercontent.com/assets/504236/20826600/51a09d22-b86c-11e6-8154-367fd2719ddd.png)

**Comment by AllanWLie** [comment]
@m-overlund Fejlen er fundet og bliver rettet i næste release. Tak for hjælpen.
