### ISSUE TITLE
Invalid method Mage_Adminhtml_Model_Session::addInfo

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#14]
Når vi annullerer en ordre kommer følgende fejl:

Invalid method Mage_Adminhtml_Model_Session::addInfo(Array ( [0] => Betalingen er annuleret ) )

![image](https://cloud.githubusercontent.com/assets/504236/20829107/eb1c94a2-b87a-11e6-807e-a200225c592b.png)

**Comment by AllanWLie** [comment]
@m-overlund Fejlen er fundet metoden skulle ændres fra AddInfo til AddSuccess. Denne ændring kommer med i næste release
