### ISSUE TITLE
"Rediger ordre"-knap mangler

### ISSUE THREAD

**Issue by kbhansen** [ePay/magento#15]
På ordrer gennemført med ePay-betaling mangler knappen "Rediger" under ordrebehandling på ikke-afsluttede ordrer. Knappen forsvandt efter opgradering fra v.2.6.5 til 2.7.0
![image](https://cloud.githubusercontent.com/assets/3779532/20834831/940494e0-b897-11e6-8be7-1cf7f9821be1.png)

**Comment by AllanWLie** [comment]
@kbhansen Vi fjernede med vilje knappen fra version 2.7.0 da funktionen indeholdte nogle uhensigtsmæssigheder. Disse er nu rettet og funktionen kommer tilbage i næste release.
