### ISSUE TITLE
PaymentRequest - betaling bliver ikke registreret i Magento

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#16]
Har oprettet en betalingsanmodning på en autocanceled ordre.
Kunden betaler betalingsanmodningen, men ordren står stadig som annulleret og uden betaling tilknyttet ordren. Betalingsanmodningen fremgår også stadig som ispaid = 0.

Betalingen er gået fint igennem i ePay backend og status på betalingsanmodningen er også skiftet til closed, i Magento.

Der er ikke nogen entries i ePay tabellen i databasen, til denne ordre, andet end den der er skabt da kunden forgæves forsøgte at betale normalt (kun increment_id/ordrenummer fremgår)

(ePay v. 2.7.2)

![screen shot 2016-12-05 at 19 46 35](https://cloud.githubusercontent.com/assets/504236/20898128/80787b18-bb25-11e6-8f38-6e6fa2c7fb1c.png)
![screen shot 2016-12-05 at 19 46 55](https://cloud.githubusercontent.com/assets/504236/20898129/808be8ec-bb25-11e6-8db5-1abe5b057b52.png)
![screen shot 2016-12-05 at 19 47 03](https://cloud.githubusercontent.com/assets/504236/20898131/80922e1e-bb25-11e6-9b20-3f3a048f8afd.png)
![screen shot 2016-12-05 at 19 47 18](https://cloud.githubusercontent.com/assets/504236/20898365/54e242a8-bb26-11e6-9862-fbc3f3ee4d6d.png)

![screen shot 2016-12-05 at 20 00 59](https://cloud.githubusercontent.com/assets/504236/20898175/ab3cf018-bb25-11e6-8ca2-2b005c39ed89.png)

**Comment by AllanWLie** [comment]
@m-overlund Det tyder på at du ikke modtager callbacken. Når Callback rammer jeres shop, bliver transaktionsId'et sat så du kan se betalings informationer, "isPaid" bliver også sat her, databasen bliver opdateret og tilsidst bliver order statusen ændret.  Det skal dog tilføjes at hvis orden er annulleret så bliver statusen for ordren ændret, men dine produkt linjer vil forblive annulleret. 

For at teste nærmere skal jeg bruge flere informationer om din kunde. Du kan oprette en supportsag på support@bambora.com

**Comment by AllanWLie** [comment]
@m-overlund Når en order er canceled burde du ikke kunne oprette en betalings anmodning (Knappen burde ikke være synlig (Det er den ikke når jeg tester))

**Comment by m-overlund** [comment]
Ok. Knappen kommer i hvert fald også frem på (auto)canceled ordrer

**Comment by AllanWLie** [comment]
@m-overlund Dette er rettet og kommer med i næste release.  Igen tak for info
