### ISSUE TITLE
Mage_Core_Exception: Ugyldig bloktype: Mage_Adminhtml_Block_Empty_View_Plane

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#17]
modulet smider core exceptions:

	2016-12-05T19:13:35+00:00 ERR (3): 
	Mage_Core_Exception: Ugyldig bloktype: Mage_Adminhtml_Block_Empty_View_Plane in app/Mage.php:595
	Stack trace:
	#0 app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException('Ugyldig bloktyp...')
	#1 app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Mage_Adminhtml_...', Array)
	#2 app/code/core/Mage/Adminhtml/Block/Widget/View/Container.php(61): Mage_Core_Model_Layout->createBlock('adminhtml/empty...')
	#3 app/code/core/Mage/Core/Block/Abstract.php(297): Mage_Adminhtml_Block_Widget_View_Container->_prepareLayout()
	#4 app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Codnitive_Extifcon_Model_Core_Layout))
	#5 app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('epay/adminhtml_...', 'paymentrequest_...')
	#6 app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('epay/adminhtml_...', 'paymentrequest_...')
	#7 app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
	#8 app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
	#9 app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
	#10 app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
	#11 app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
	#12 app/code/local/Mage/Epay/controllers/Adminhtml/PaymentrequestController.php(33): Mage_Adminhtml_Controller_Action->loadLayout()
	#13 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Epay_Adminhtml_PaymentrequestController->viewAction()
	#14 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
	#15 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
	#16 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
	#17 app/Mage.php(683): Mage_Core_Model_App->run(Array)
	#18 index.php(148): Mage::run('base', 'website')
	#19 {main}

**Comment by AllanWLie** [comment]
@m-overlund Har du Cleared Magento cachen ?

**Comment by m-overlund** [comment]
Undersøger nærmere, og vender tilbage hvis det stadig er et problem.
