### ISSUE TITLE
2.7.4 - Payment information to separate tab

### ISSUE THREAD

**Issue by kbhansen** [ePay/magento#18]
Er denne fjernet fra 2.7.4 igen "Added ePay payment information to separate tab" –  introduceret i 2.7.0?
Det fremgår ikke af releases.

**Comment by AllanWLie** [comment]
@kbhansen Den er ikke fjernet.  For hver release vi laver skriver vi kun de nye ting som er sket, så du kan se hvad der er rettet, tilføjet eller fjernet i forhold til de forgående releases.

**Comment by kbhansen** [comment]
OK – men efter opgradering fra 2.7.0 til 2.7.4 forsvinder den. Reproduceret på flere sites, uafhængigt af hinanden.

**Comment by AllanWLie** [comment]
@kbhansen I version 2.7.1 tilføjede vi mulighed for at slå det fra. Hvilket vil sige at hvis du i modulets konfiguration har sat "Process payments from within the order administration of Magento:" til "No" bliver den ikke vist på order siden i administrationen

**Comment by kbhansen** [comment]
Det var lige der den gemte sig. Issue closed :-)
