### ISSUE TITLE
kortgebyr varelinien tilføjes ordrer uden kortgebyr

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#20]
Der er vel ikke nogen grund til at tilføje en kortgebyr varelinien, hvis der ikke er noget kortgebyr på ordren?

![screen shot 2016-12-19 at 19 06 56](https://cloud.githubusercontent.com/assets/504236/21323573/6e9c843a-c61e-11e6-9b83-f4bae8a256a7.png)

**Comment by AllanWLie** [comment]
@m-overlund Det har du helt ret i, havde rettet det i et andet modul, men ikke fået rettelsen med her over. Det kommer i næste release ( i dag) sammen med nogle andre ting.  I mellemtiden kan du i modulets config slå kort gebyr fra hvis det genere dig.

**Comment by m-overlund** [comment]
Ok. jeg venter. Vi har kortgebyr på nogle korttyper men ikke andre - derfor det er relevant.

**Comment by AllanWLie** [comment]
@m-overlund Så er det fikset, og en ny release er her: https://github.com/ePay/magento/releases/latest

Tak for hjælpen.

-Allan
