### ISSUE TITLE
Rediger ordre: Betaling bliver annulleret

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#21]
Når jeg redigerer en ordre, bliver betalingen annulleret.
Betalingen følger ikke med den nye ordre Magento genererer, som den skulle.

**Comment by AllanWLie** [comment]
@m-overlund 
Hej,

Det er standard Magento adfær at når en order bliver redigeret så kalder Magento Cancel action og når Magento kalder denne action kalder den også Void action'en. 

Du kan i Magento (Mage_Sales_Model_Order_Payment) på linje 865 se at når Cancel() methoden bliver kaldt, bliver Void også kaldt.

Med venlig hilsen
Allan

**Comment by m-overlund** [comment]
Men var det ikke netop en funktion i modulet, at man skulle kunne redigere en ordre og betalingen så følger?

`Hvis du redigerer en ordre, føres ePay-transaktionen automatisk med til den nye ordre. `
http://www.magento.dk/da/opsaetning#2558

**Comment by AllanWLie** [comment]
@m-overlund 
Det er korrekt at vi havde før havde denne kode i vores Cancel logik:
https://github.com/ePay/magento/blob/d89d75edf9630f5e5f44f3868118363e2745d50c/app/code/local/Mage/Epay/Model/Standard.php#L675

Grunden til at vi har fjernet denne funktion er at værdien af "relation_child_real_id" er null da magento kalder $order->Cancel() før den opretter den nye order. Se Magento kilde kode Mage_Adminhtml_Model_Sales_Order_Create linje: 1523 / 1548

Når "releation_child_real_id er null kan vi ikke kopier payment objektet fra den gamle order til den nye da vi på dette tidspunkt ikke kender den nye order.

Vi har dog ikke i nu opdateret vores dokumentation.

Men hvis du har en løsning til dette så er du velkommen til at lave en pull reguest

**Comment by lsv** [comment]
Er der mulighed for at lave så den IKKE annuller betalingen i epay? - Fx en tjekboks i opsætningen
- Jeg vil nu mene dette er ret kritisk, da ordrer bliver ændret ret ofte

**Comment by AllanWLie** [comment]
Hej @lsv
Det kunne man som sådan godt lave. Det vil dog betyde at du ikke kan bruge funktionerne Invoice, Creditmemo eller Void i magento's backoffice for den ny oprettede order da den ikke længere indeholder transaktions oplysningerne.

**Comment by m-overlund** [comment]
Umiddelbart synes jeg det vil være en bedre løsning, selvom det ikke er helt optimalt.
Pt. kan vi ikke bruge rediger ordre knappen, da vi jo så skal have alt bøvlet med kunden og forklare hvorfor de skal betale for en vare som de har betalt for én gang før.

Så vil man stadig kunne hæve pengene manuelt - modsat i dag.

**Comment by AllanWLie** [comment]
Okay. Vi overvejer lige en løsning som muligvis kommer med i næste release. 

-Tak

**Comment by m-overlund** [comment]
En løsning kunne måske være at lave en "reassign payment" knap, som kommer frem på ordrer som har en parent order, samt en betaling på parent order.

Dvs. workflowet er at man redigerer ordre 10000001 og dermed får en ny 10000001-xx ordre som normalt. 
På den nye ordre kan man så trykke "Reassign Payment" for at tilknytte betalingen fra hovedordren, til den nye, redigerede ordre.

Det kunne måske være lettere at løse den vej rundt, så du undgår logikken omkring edit knappen?

**Comment by AllanWLie** [comment]
@m-overlund 
Det lyder som en mulighed og er hermed noteret. Du er selvfølgelig også velkommen til at lave en pull request hvis du vil have tingene til at gå hurtigere :)

Kan du have en god dag.

-Allan

**Comment by lsv** [comment]
Hvad med muligheden at der gemmes en "deleted" status i epay_status tabellen
og når en ny ordre oprettes tjekkes ordrens parent, hvis en parent eksisterer så gå ind i epay_status tabellen, og fjern "deleted" status, og evt. ændre ordre nummeret til det nye ordre id.

I "ny ordre" listeneren kan man evt kopierer payment til den nye ordre?

Dette kræver naturligvis et cronjob som sørger for at "deleted" statusser bliver slettet i epay.

**Comment by AllanWLie** [comment]
Hej @lsv ,

Tak for dit input, det vil blive taget med i overvejelserne når vi begynder at implementere en løsning for dette issue. 

Kan du have en god dag.

-Allan

**Comment by AllanWLie** [comment]
@m-overlund and @lsv 
Vi har nu implementeret de ønskede funktioner. 
I modulets konfiguration (nederest) kan i nu slå sletning af betalingen fra når i editer en order. Samtidig kan i når denne konfiguration er slået fra, flytte betalingen fra den oprindelige order til den ny (-x) order. (Der er nu en knap ved siden af "invoice" osv. )

Link til release: https://github.com/ePay/magento/releases/latest

Med venlig hilsen
Allan

**Comment by lsv** [comment]
Awesome! - Tak!
