### ISSUE TITLE
Table not found hvis tabeller har prefix

### ISSUE THREAD

**Issue by kattehus** [ePay/magento#22]
Hej,
En af vores kunder har i dag forsøgt at installerer version 2.7.8 på deres magento løsning. Deres løsning er sat op med prefix på deres tabeller.

Det førte til følgende fejl:
`a:5:{i:0;s:221:"Error in file: "/home2/deletryk/public_html/app/code/local/Mage/Epay/sql/epay_setup/mysql4-install-2.7.8.php" - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'deletryk_mg1.core_config_data' doesn't exist";i:1;s:1021:"`

Jeg kan se, at der i mysql4-install-2.7.8.php, linje 47, er en linje til at fjerne nogle entries fra core_config_data tabellen - denne linje fejler, da den tabel ikke findes (i denne kundes tilfælde hedder tabellen mg_core_config_data)

Er det fordi de burde have installeret version 2.6.4 først?

**Comment by AllanWLie** [comment]
Hej @kattehus 

Det er fordi vores modul ikke understøtter brugen af db præfix.

**Med venlig hilsen**
Allan

**Comment by kattehus** [comment]
Hej @AllanWLie,

Tak for det hurtige svar.
Har i planer om at understøtte prefixes?

Vi benytter nogle systemer til bl.a. at holde løsninger up-to-date og lave backups, såsom installatron. Disse opretter som udgangspunkt løsninger med prefixes, og inkluderer ikke automatisk tabeller, som ikke er prefixede, i deres backups.

**Comment by AllanWLie** [comment]
Hej igen @kattehus 

Jeg vil ikke afvise om vi på sigt kommer til at understøtte det, men for nu er der ikke planer om understøttelse, da vi ikke i nu har fundet en løsning som ikke påvirker vores andre kunder som bruger modulet uden prefix. 

Kan du have en god dag.

-Allan

**Comment by kattehus** [comment]
Hej igen,

Tak igen. God dag til dig, også. :)
