### ISSUE TITLE
Hvor bliver $actionOrder defineret?

### ISSUE THREAD

**Issue by puntable** [ePay/magento#23]
canAction() tager $actionOrder som parameter, men hvor er denne defineret?

**Comment by AllanWLie** [comment]
Hej @puntable 

Funktionen er defineret her: https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L151

og bliver brugt her: https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L177

og her: 
https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L272

og her:
https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L368

**Comment by puntable** [comment]
Hej

Det var variablen $actionOrder jeg mente. Den er null?

**Comment by AllanWLie** [comment]
Funktionen canAction($actionOrder) bliver kaldt fra de tre før nævnte metoder, hvor de giver et order object som input til funktionen.

**Comment by puntable** [comment]
$actionOrder er `null` når du tilgår ordredetaljer siden?

`Fatal error: Call to a member function getIncrementId() on null in /public_html/app/code/local/Mage/Epay/Model/Standard.php on line 156`

**Comment by AllanWLie** [comment]
Det tyder på at der er en fejl i _data["info_instance"]->getOrder();
eks Linje:  https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L175

Vi oplever ikke denne fejl og vi har ikke fået indrapoteret andre ligende fejl så jeg ville skyde på at fejlen ligger i din magento integration. da _data["info_instance"]->getOrder(); er data og methode suppleret fra Magento.

Du må prøve at debugge koden og se om du kan finde hvorfor _data["info_instance"] ikke indeholder dit order object.

Hvilken version af Magento bruger du og hvilken version af PHP bruger du (gætter på 5.4). ?

**Comment by puntable** [comment]
Har opdateret modulet på 3 shops idag. 
2x 1.7.0.2 (PHP 5.6.27)
1x 1.8.0.0 (PHP 5.3.3)
Samme fejl på alle sammen. Jeg prøver at undersøge nærmere. Du hører fra mig når jeg finder årsagen.

**Comment by AllanWLie** [comment]
Det kan have noget at gøre med dine magento versioner. Vi bruger magento 1.9.x.x så muligvis findes order objektet ikke i de tidligere versioner.

**Comment by puntable** [comment]
`$this->_data["info_instance"]->getOrder()` indeholder fint order objekt. 

Problemet er, at `$actionOrder` er `null` når `canAction()` bliver kaldt. `canCapture()` returnerer en boolean, korrekt?

Dette ser ud til at fungere:

```
private function canAction()
    {
        $actionOrder = $this->_data["info_instance"]->getOrder();
		
        $read = Mage::getSingleton('core/resource')->getConnection('core_read');
	$row = $read->fetchRow("select * from epay_order_status where orderid = '" . $actionOrder->getIncrementId() . "'");
		if($row["status"] == '1')
		{
			return true;
		}

        return false;
    }
```

**Comment by AllanWLie** [comment]
canAction bliver også kaldt fra canReund og canCancel, er order objectet også eksisterende ved disse metoder ?

**Comment by puntable** [comment]
Det er `$payment->getOrder()` der returnerer null i `canVoid`.

**Comment by AllanWLie** [comment]
Okay det har muligvis noget at gøre med din version af magento af gøre siden vi ikke oplever problemer.  Min anbefaling er at du implementere et null check i canVoid($payment) hvor hvis $payment->getOrder() returnere null sætter du voidOrder ligesom i funktionerne canCaptutre og canRefund

**Comment by puntable** [comment]
Hej Allan

Det her ser ud til at fungere:
   ```
public function canVoid(Varien_Object $payment)
{			
    if($payment->getOrder() === null)	
        {
	    $paymentOrder = $this->_data["info_instance"]->getOrder();
	}
	else 
        {
		$paymentOrder = $payment->getOrder();
	}
        if($this->_canVoid && $this->canAction($paymentOrder))
        {
            return true;
        }
    return false;
}
```
Skal jeg lave en pull request?

**Comment by AllanWLie** [comment]
Hej @puntable 

Din logik ser fin ud, jeg har dog refactored den lidt:
*****************
public function canVoid(Varien_Object $payment)
{	
	$voidOrder = $payment->getOrder();		
	if(!isset($voidOrder))	
        {
    	       $voidOrder = $this->_data["info_instance"]->getOrder();
 	}
 	if($this->_canVoid && $this->canAction($voidOrder))
        {
    	       return true;
        }

 	return false;
}
*******************

Du må gerne teste og lave en pull request med den refactored kode

**Comment by puntable** [comment]
Hej Allan

Jeg har testet på en 1.7.0.2 og det fungerer fint. Har lavet en pull request.

**Comment by AllanWLie** [comment]
@puntable 
Super, den er her med merged.
