### ISSUE TITLE
Chrome autofiller "Remote password" og "Auth mail"

### ISSUE THREAD

**Issue by CMeldgaard** [ePay/magento#26]
Hvis man har gemt login til magento backend, bliver "Auth mail" udfyldt med ens brugernavn og "Remote password" med ens password. Det betyder at hvis man ikke husker at rette dette bliver ens "Remote password" overskrevet hver gang man laver ændringer til ePay settings i backend.

**Comment by AllanWLie** [comment]
Hej @GeekMediaDK 
Vi er opmærksom på dette, men umildbart har vi ikke en løsningen da felterne er standard magento input felter.
