### ISSUE TITLE
Er version 2.6.4 eller nyere påkrævet?

### ISSUE THREAD

**Issue by LBTS** [ePay/magento#27]
Sidder med en shop der kører version 2.6.3 (beta). 
Kan jeg opdatere til seneste version uden problemer? 
Eller skal jeg tage opgradere til 2.6.4 (eller 2.6.6, som er seneste release før min. 2.6.4 bliver påkrævet), før jeg opdaterer til seneste version?  

Har før siddet med Magento shops, hvor man med ældre version er nødt til at tage opdateringerne over flere omgange, da de nyere versioner er afhængige af ændringer der er blevet indført i tidligere opdateringer. Så hvis man er langt bagefter, kan man ikke bare hoppe til seneste version.

**Comment by Aplbo** [comment]
Jeg har opdateret fra 2.6.3 til 2.6.4 og herefter til 2.8.1 - for netop at undgå fejl grundet dependencies. Det har fungeret uden problemer.

**Comment by LBTS** [comment]
Gjorde som ovenstående og fungerede uden problemer.
