### ISSUE TITLE
Betalings informationer - Svindelkontrol - mangelfulde informationer

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#29]
Under Betalingsinformationerne for en ordre kan man ikke altid se hvorfor en ordre er markeret som svindel. 

Ofte står der blot:
`Dette kort er blevet brugt 1 gang(e) de sidste 24 timer`

Logger jeg ind på ePay kan jeg oftest se at det er pga. flere betalinger fra samme IP adresse - den information mangler i Magento.

`Within the past 24 hours, this payment card has been used 2 time(s), and payments were completed from the IP address (xx.xx.xx.xxx) 3 time(s). The payment was completed from  Denmark`

Antallet af betalinger fra samme kort stemmer desuden ikke altid overens med ePay administrationen.

**Comment by AllanWLie** [comment]
Hej @m-overlund 


_Ofte står der blot:
Dette kort er blevet brugt 1 gang(e) de sidste 24 timer_

Dette er en fejl i modulet. Her er der brugt den forkerte tekst streng.

_Logger jeg ind på ePay kan jeg oftest se at det er pga. flere betalinger fra samme IP adresse - den information mangler i Magento.
Within the past 24 hours, this payment card has been used 2 time(s), and payments were completed from the IP address (xx.xx.xx.xxx) 3 time(s). The payment was completed from Denmark_

Disse informationer er ikke tilgængelige via vores API så derfor kan vi ikke vise dem i modulet.

Vi har nu frigivet en ny version af modulet.
