### ISSUE TITLE
Betaling bliver ikke registreret på MobilePay

### ISSUE THREAD

**Issue by puntable** [ePay/magento#31]
Når der bliver betalt med MobilePay bliver der ikke oprettet betaling i Magento.
Magento: 1.9.3.6
Epay: 2.8.6
Det fungerer fint på kreditkort.

Redirect 1
`https://publicmobilepay.danskebank.com/P2O/Router/Address/MerchantJumpPage.aspx?LanguageCode=da&CountryCode=DK&PaySessionToken=2017-09-27-23.09.44.906206&Scenario=P`

Redirect 2 
`https://ssl.ditonlinebetalingssystem.dk/integration/ewindow/Default.aspx?accept=1&sessionid=62162304&sessionkey=397FA63F8392243EC6404D9B77597652-F5485E61715972AA4709B573646B6030B5928B17424705933711F20E8087221D&txnid=120817793&orderid=300000089&amount=29995&currency=208&date=20170927&time=2138&txnfee=0&paymenttype=1&cardno=457181XXXXXX8666&hash=07fd505c3ea267876894038e7cdb2c40`

De tomme rækker i screenshot er MobilePay betalinger.
![epay](https://user-images.githubusercontent.com/11092272/30932687-931d1148-a3c8-11e7-815e-8e9848c3af81.png)

**Comment by AllanWLie** [comment]
Hej @puntable 

For at vi kan hjælpe dig med dit issue, skal du oprette en support ticket ved at sende en mail til support@bambora.com

**Comment by puntable** [comment]
Blot så andre kan finde en løsning på samme problem.
Det ser ud til at callbacks bliver foretaget forskelligt afhængigt af om det er kreditkort eller mobilepay.

Ved kreditkort betalinger ser det ud til at der bliver foretaget 2 callbacks

```
#1 /epay/standard/callback/?txnid=xxxxxxxxx...
#2 /epay/standard/callback?txnid=xxxxxxxxx...
```

Ved mobilepay
```
#1 /epay/standard/callback/?txnid=xxxxxxxxx
```

Er der opsat noget redirect med trailing slash ifm. SEO eller lign. kan det betyde at mobilepay betalinger ikke bliver registreret pga. ...callback**/**?txnid=...

**Comment by AllanWLie** [comment]
@puntable 

Callbacks fra mobile pay og betalings kort er de samme (Der skal dog kun komme 1 stk pr. betaling, med mindre de fejler (hvis din shop returnere 500 i response code)) og vi har ikke oplevet andre med ligende problemer med Magento. Dette betyder dog ikke at der ikke er en fejl et eller andet sted. Vi skal have dig til at oprette en support ticket, så vi kan se alle dine data inkl. callbacks og derigennem teste hvad der går galt for dine mobile pay betalinger. 

Vi har dog oplevet problemer med callbacks på andre shops hvor kunder har installeret div. plugins som redirecter vores callback. Men da dine kreditkort betalinger går igennem, burde det ikke være det. Du kan evt. prøve at slå dine andre plugins fra og se om fejlen fortsætter.

**Comment by puntable** [comment]
Hej Allan

Jeg løste det selv ved at ignorere callback url med trailingslash. 
Ikke desto mindre var det betalingsmetoden (kreditkort vs mobilepay) der afgjorde om den gik igennem da jeg havde opsat redirect. Så en eller anden ekstern faktor har med sikkerhed spillet ind.

Du kan selv teste, hvis du laver en regel (i .htaccess eller modul) der tvinger slut trailing slash i url væk (https://minshop.dk/ => https://minshop.dk) med 301 redirect. Så vil du opleve præcis samme problem som jeg beskriver.

**Comment by AllanWLie** [comment]
Hej @puntable 

Super fedt. Jeg giver informationen videre til vores Support afdeling, så de i fremtiden kan hjælpe andre kunder med samme problem. 

Tak for hjælpen og må du have en rigtig god weekend

**Med venlig hilsen**
Allan Lie
