### ISSUE TITLE
Flytning af betaling virker kun ved redigering af original ordre

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#32]
Genskab:
1. Rediger en ordre
2. Flyt betalingen fra tidligere ordre
3. Rediger den nye ordre

Resultat:
Det er ikke muligt at flytte betalingen fra tidligere redigeret ordre.

Forventet resultat:
Man kan flytte betalingen fra tidligere redigeret ordre.

**Comment by AllanWLie** [comment]
Hej @m-overlund 

Modulet understøtter ikke flytning af betalinger fra redigeret ordre.

Vi har noteret dit ønske om at kunne flytte betalingen fra en redigeret ordre, og denne funktion vil muligvis komme med i en fremtidig version af modulet.

-Allan

**Comment by AllanWLie** [comment]
Hej @m-overlund 

Vi har nu lavet en ny release hvor man nu kan flytte en betaling fra en allerede redigeret ordre. 
https://github.com/ePay/magento/releases/latest
