### ISSUE TITLE
Ordre bliver annulleret inden betaling

### ISSUE THREAD

**Issue by puntable** [ePay/magento#33]
Hej Allan

Jeg oplever ofte hos flere forskellige kunder, at ordren bliver annulleret inden betalingen bliver registreret. "Auto cancel" er slået fra og det sker på på forskellige versioner af modulet.
Er det pga. kunden fumler rundt med betalingsvinduet og kommer til at lukke dem eller har du evt. en anden forklaring på hvorfor det sker?

![epay](https://user-images.githubusercontent.com/11092272/35813815-d9e33cd2-0a94-11e8-9bb3-555d47feebc7.png)

**Comment by AllanWLie** [comment]
Hej @puntable 

Selv hvis "Auto cancel" er aktiveret vil funktionen ikke annullere ordren inden for det tidsrum dit billede beskriver. Det tyder på at (som du selv skriver) at din kunder går tilbage i browseren, hvilket til tider kan påvirke at betalingsvinduet bliver åbnet igen, hvor efter de trykker på cancel (Det røde kryds). 

Vi har i de nyeste versioner af modulet, forsøgt at forhindre dette, men det er, som du oplever, ikke altid det lykkes.  Umildbart har vi ikke en solid løsning til problematikken.

Kan du have en god dag.

-Allan
