### ISSUE TITLE
New version 2.8.7 breaks Composer installations

### ISSUE THREAD

**Issue by wexo-team** [ePay/magento#34]
52ac1882c1bc6e67ffe7d522526b535b3b8133d7 removes file that is needed for Composer support to work.

The file `modman` is needed to Composer to understand where do deploy the modules files into the folder structure of Magento (this missing is what is breaking stuff)  
The file `.gitignore`'s one line `/vendor/` prevents developers from accidentally adding the source files for the dev modules `magento-ecg/coding-standard` and `magento/marketplace-eqp` to the Git repo

After restoring the files then please also remove v2.8.7 of the module from GitHub to avoid it breaking development shops and less vigilant Composer updates of production shops.

**Comment by AllanWLie** [comment]
Hi @wexo-team 

We will look into this and correct it. 

Best regards
Allan

**Comment by AllanWLie** [comment]
Hi again,

Now we have restored the files, removed release 2.8.7 and created a new release 2.8.8.

Thank you for spotting the error.

Best regards 
Allan
