### ISSUE TITLE
payment cc_number_enc gemmes ukrypteret

### ISSUE THREAD

**Issue by m-overlund** [ePay/magento#37]
Kortnummer bliver gemt ukrypteret i databasen, i Magentos payment tabel.
Det skaber konflikter når andre moduler forsøger at dekryptere værdien inden den hentes ud.

Feltet er lavet til at indeholde en krypteret værdi.

Det bør krypteres/dekrypteres via Magento's indbyggede funktioner til det:
`Mage::helper('core')->decrypt`
`Mage::helper('core')->encrypt`

## Info
tabel: `sales_flat_order_payment`
felt `cc_number_enc`

https://github.com/ePay/magento/blob/d9ac804510ae6961141482306de210cf7fbefd52/app/code/local/Mage/Epay/controllers/StandardController.php#L379

**Comment by AllanWLie** [comment]
Hej @m-overlund 

Vi har nu fikset dit issue og en ny release kan findes her: https://github.com/ePay/magento/releases/latest

Tak for at udpege fejlen.

Med venlig hilsen
Allan - Bambora
