### ISSUE TITLE
Redirect advarsel ved mobilvindue (feature request)

### ISSUE THREAD

**Issue by puntable** [ePay/magento#40]
Efter Google har lavet en opdatering af Google Chrome Mobile, så bliver man nu mødt af en sikkerhedsadvarsel, hvis man bruger mobilvenligt betalingsvindue, pga. redirect til andet domæne. 
Denne nye "feature" fra Google, kræver at den besøgende aktivt skal acceptere redirect (trykke ok), hvilket mange kunder ikke forstår og derfor falder fra.
Hvis man bruger standard betalingsvindue vises denne advarsel ikke, da betaling foregår i iframe, men det fungerer ikke optimalt på mobil.
Kan i ikke opdatere standard betalingsvinduet så det fungerer på mobil (responsivt design/layout) eller give jeres merchants adgang til CSS opdateringer af betalingsvinduet i deres Epay backend?

**Comment by AllanWLie** [comment]
Hej @puntable 

Vi er opmærksom på problemet og arbejder på en løsning.

Kan du have en god dag.

Med venlig hilsen
Allan - Bambora
