### ISSUE TITLE
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function

### ISSUE THREAD

**Issue by sicet7** [ePay/magento#43]
["app/code/local/Mage/Epay/Block/Adminhtml/Sales/Order/View/Tab/Info.php" Line 248](https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Block/Adminhtml/Sales/Order/View/Tab/Info.php#L248) Makes use of the method defined in: [app/code/local/Mage/Epay/Model/Standard.php Line 495](https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Model/Standard.php#L495) which requires 2 Arguments, but only 1 is passed, the second argument should be the store id of the order.
The line in ["app/code/local/Mage/Epay/Block/Adminhtml/Sales/Order/View/Tab/Info.php"](https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/Block/Adminhtml/Sales/Order/View/Tab/Info.php#L248) can be modified to:
`$res .= "<tr><td colspan='2'>" . $paymentobj->getEpayErrorText($result->epayresponse,$this->getOrder()->getStoreId()) . "</td>";` to make it work correctly and not throw a fatal error.

**Comment by AllanWLie** [comment]
Hi @sicet7 
We will look into this and fix this bug in the next release.

Thank you for posting the issue.

Have a great day.

Best regards
Allan - Bambora

**Comment by AllanWLie** [comment]
Hi @sicet7 

We have now fixed the issue you found. 
https://github.com/ePay/magento/releases/latest

Thank you and may you have a good day.

Best regards
Allan - Bambora
