### ISSUE TITLE
Minor Notice Fix

### ISSUE THREAD

**Issue by sicet7** [ePay/magento#44]
`2019-06-05T10:55:47+00:00 ERR (3): Notice: Undefined index: paymentrequest  in /var/webapps/incover/magento/vendor/epay/magento/app/code/local/Mage/Epay/controllers/StandardController.php on line 324
`

Just changing: 
`if ($getQuery['paymentrequest'] && strlen($getQuery['paymentrequest']) > 0) {` 
to 
`if (isset($getQuery['paymentrequest']) && strlen($getQuery['paymentrequest']) > 0) {` in https://github.com/ePay/magento/blob/master/app/code/local/Mage/Epay/controllers/StandardController.php#L324

Fixes this, but this is not a critical issue, this is just to stop it from filling logs with the error :-)

**Comment by AllanWLie** [comment]
Hi @sicet7 

Thank you for reporting this. I have added it to our backlog and it will be changed in the next release.

Have a good day.

Best regards
Allan
