### ISSUE TITLE
Respecting state changes

### ISSUE THREAD

**Issue by WebKenth** [ePay/magento#46]
When redirected to the payment gateway the order is left in the "new" state, this causes confusion as it is counted as a new order when it is infact pending payment. The only thing this module is changing is the status of the order

There is a very distinct difference between Status and State in which any service integrated with magento will choose to adhere to the state of the order rather than the status. Since Statusses can be user defined.

In `app/code/local/Mage/Epay/controllers/StandardController.php:405` you change the order state to processing once a transaction has been confirmed from the gateway
```
$order->setState(Mage_Sales_Model_Order::STATE_PROCESSING, $orderStatusAfterPayment, $message, false);
```

Since an order is placed in the new state there no way to differentiate between an order which has been created by other means or an order which has been abandoned ( This can quickly be tested by going to checkout, opening the gateway and closing the browser window )
You can only verify this by checking the order comments or by attempting to capture any payments on the order ( this will fail ).

I propose changing your `app/code/local/Mage/Epay/Model/Observer.php:147`
from: 
```
    public function orderPlacedAfter($observer)
    {
        /** @var Mage_Sales_Model_Order */
        $order = $observer->getOrder();
        if ($this->validatePaymentMethod($order)) {
            $order->addStatusHistoryComment(Mage::helper('epay')->__("The Order is placed using ePay Online payment system and is now awaiting payment."))
                ->setIsCustomerNotified(false);
            $order->save();
        }
    }
``` 
to
```
    public function orderPlacedAfter($observer)
    {
        /** @var Mage_Sales_Model_Order */
        $order = $observer->getOrder();
        if ($this->validatePaymentMethod($order)) {
            $comment = Mage::helper('epay')->__("The Order is placed using ePay Online payment system and is now awaiting payment.");
            $order->setState(Mage_Sales_Model_Order::STATE_PENDING_PAYMENT,$order->getStatus(),$comment,false);
            $order->save();
        }
    }
```

This will put the order in a pending_payment state while the payment window is open.

This now makes it possible for integrations who listen on states to understand what is happening to the order

Yes, this could be solved by the integrations spending multiple hours to creating `If this then that` logic however i believe that setting the state of the order to what is actually happening is the better course of action :) 

Side Note: the dropdown in your configuration is using the core magento sourcemodel ( which is should)
`<source_model>adminhtml/system_config_source_order_status</source_model>`
The source model however is not showing the `Mage_Sales_Model_Order::STATE_PENDING_PAYMENT` as an option by default
`app/code/core/Mage/Adminhtml/Model/System/Config/Source/Order/Status.php:35`

**Comment by AllanWLie** [comment]
Hi @WebKenth ,

Thank you for informing us about this issue. We will look into it and if applicable add it to the next deploy.

Have a good day.

Best regards 
Allan - Bambora Online A/S

**Comment by AllanWLie** [comment]
We have now corrected the issue. 
The new release is here: https://github.com/ePay/magento/releases/latest
