### ISSUE TITLE
Version 3.2 is tagged, but not in composer.json

### ISSUE THREAD

**Issue by karbowiak** [ePay/magento#50]
Hi there.

It seems in the tagging of 3.2, the version number in composer.json wasn't updated - so it still says 3.1.1

**Comment by AllanWLie** [comment]
Thank you for correcting this.

Best regards
Allan - Bambora Online A/S

**Comment by karbowiak** [comment]
@AllanWLie you need to either redo the 3.2.0 tag, or bump it all up to 3.2.1 / 3.2.0.1 (including composer.json)

Otherwise the fix don't work :P
